### ISSUE TITLE
GitHub issues用のテンプレート作る必要あるか？

### ISSUE THREAD

**Issue by yofukami** [icat-lab/g4n#10]
必要ですよね、、、？

**Comment by Gucchiy** [comment]
@yofukami テンプレート・・とはどんなのイメージしています？

**Comment by yofukami** [comment]
@Gucchiy Aroundでお話させていただけませんか?
たたき台としてとりあえず、こういうのを作ってみました。

* https://github.com/icat-lab/ay2021spring_icatlab/blob/main/templete_issues
* https://github.com/icat-lab/ay2021spring_icatlab/issues/1

**Comment by Gucchiy** [comment]
@yofukami OK です！後はこちらのテンプレートを文書上に展開するだけなので、まずは書面にしてみますね。（私がテンプレートを用意するようならヒアリングしないとな、と言う粒度だったので）とりあえず、そちらをご覧になってみてくださいませ。今日の夜半に対応します

**Comment by yofukami** [comment]
@Gucchiy ありがとうございます! 
こっちも作りました。併せて参照ください。
https://github.com/icat-lab/ay2021spring_icatlab/issues/2

**Comment by Gucchiy** [comment]
@yofukami こちらの自己紹介は私も書いた方がよいですか？
https://github.com/icat-lab/ay2021spring_icatlab/issues/2

**Comment by yofukami** [comment]
@Gucchiy できれば、学部新入生向けの自己紹介を、簡単にしていただければありがたいです。

**Comment by Gucchiy** [comment]
@yofukami 対応しました！
icat-lab/ay2021spring_icatlab#2

**Comment by yofukami** [comment]
@Gucchiy ありがとうございます!!
