### ISSUE TITLE
GitHub の使い方ドキュメントの作成

### ISSUE THREAD

**Issue by Gucchiy** [icat-lab/g4n#8]
学生向けに GitHub の使い方ドキュメントを md ファイルで提供します。2021-03-20 現在の要件は下記通り。

- 文系且つ初心者向け
- 最初は Repository はいじらない
- Issues の利用が基本
- Project で毎週授業のやることを掲載
  - 学生の担当者が管理してくれることを想定 
- 作成した文書は[ここ](https://github.com/icat-lab/g4n/blob/main/howto/github.md)に置きます
  - ファイルは授業開始時に授業用リポジトリにコピーする
  - ファイル構成
    - [github.md トップ ページ](https://github.com/icat-lab/g4n/blob/main/howto/github.md)
    - [github_login.md アカウントの作成](https://github.com/icat-lab/g4n/blob/main/howto/github_login.md)
    - [github_issues.md Issues を使う](https://github.com/icat-lab/g4n/blob/main/howto/github_issues.md)
    - [github_projects.md Projects を使う](https://github.com/icat-lab/g4n/blob/main/howto/github_projects.md)

**Comment by Gucchiy** [comment]
@yofukami 一通り書きましたー。
https://github.com/icat-lab/g4n/blob/main/howto/github.md
一旦、深見さんご確認くださいませ。問題あればコメントを、問題なければクローズでお願いします。なお、クローズが確認され次第、[基礎ゼミのリポジトリ/ディレクトリ](https://github.com/icat-lab/icat_lab/tree/master/basic_seminar_undergrad)へコピーを push します。
せっかく GitHub なので、直接手を入れて頂いても、commit &amp; push して頂いても問題ありません。

**Comment by yofukami** [comment]
@Gucchiy ありがとうございます! 確認しました。こちらで完成ということで、closeしようと思います。
せっかくなので、コピーをプッシュいただけませんか？
