### ISSUE TITLE
GitHub Issues投稿方法説明の資料作成と、内容検討

### ISSUE THREAD

**Issue by yofukami** [icat-lab/g4n#9]
# 盛り込むべき内容
* IssuesはWYSIWYGのUIなので、そこまでmarkdownについて詳しく伝えなくて良い？
* 担当者がCodeに集約するときにはMDを手打ちしなくてはならないので、その準備どうする？
* Codeに集約するとき、他の学生がアップしたissueをコピペすると思うのですが、editボタン押させるか？
@Gucchiy

**Comment by Gucchiy** [comment]
@yofukami 
Issues 投稿方法は、一旦こちらで書いているつもりですが、
https://github.com/icat-lab/g4n/blob/main/howto/github_issues.md
おお、なるほど。とりあえず、markdown の使い方は、以下へのリンクでどうかしら。
https://docs.github.com/ja/github/writing-on-github/basic-writing-and-formatting-syntax

**Comment by yofukami** [comment]
@Gucchiy ありがとうございます。

# Issues投稿方法
これ、下手にいちいち ay2021spring_icatlab のリポジトリに移すよりは、g4n の中にドキュメントをためていくほうが良いかも、ですね。

# Markdown投稿方法
リンクご提供ありがとうございます。こちらを確認する前に #11 にも項目作っちゃいました。ますはGitHub謹製のレファレンス使って説明した方が、GitHubのチームへのフィードバックができるという点でも良いですよね？

**Comment by Gucchiy** [comment]
@yofukami まあ、フィードバックは正直 Markdown 程度の仕様だともはや枯れてるかなと言う気もしますが、公式の方がデッドリンクしたりするリスクが少ないかな、と。それほど底の深い仕様ではないので、確実でストレートな記述が一つあれば十分のように思います（HTMLの方がよっぽど悪魔）

**Comment by Gucchiy** [comment]
@yofukami 以下のように、Issue 登録の延長で Markdown についての説明を追記しています。
https://github.com/icat-lab/g4n/blob/main/howto/github_issues.md#markdown-%E5%BD%A2%E5%BC%8F%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by yofukami** [comment]
@Gucchiy ありがとうございます。
これで大丈夫かと思いますので一度このissueはcloseしておこうと思います。
